src/apps/products/urls.py
from django.urls import path
from .views.product_compare_view import ComparisonPageView, AddToComparisonView, RemoveFromCompareView
from .views.product_view import ProductDetailView, FilteredProductListView

urlpatterns = [
    # shop url conf
    path('shop/', FilteredProductListView.as_view(), name="shop"),
    # shop by category
    path('shop/<slug:category_slug>/', FilteredProductListView.as_view(), name='shop_category'),  
    # shop by child category
    path('shop/<slug:category_slug>/<slug:child_slug>/', FilteredProductListView.as_view(), name='shop_child_category'),  
    # shop by child + brand
    path('shop/brand/<slug:brand_slug>/', FilteredProductListView.as_view(), name='shop_brand'),  
    # product details
    path('shop/product-details/<slug:category_slug>/<slug:child_slug>/<slug:product_slug>/', ProductDetailView.as_view(), name='product_details'), 

    # comparison url conf
    path('compare/', ComparisonPageView.as_view(), name='compare'),
    path('compare/add/<int:product_id>/', AddToComparisonView.as_view(), name='add_compare'),
    path('compare/remove/<int:product_id>/', RemoveFromCompareView.as_view(), name='remove_compare'),
]

src/config/urls.py
from django.contrib import admin
from django.conf    import settings
from django.conf.urls.static import static
from django.urls    import path, include

urlpatterns = [
    # admin url
    path('admin/', admin.site.urls),    

    # google authentication
    path('accounts/', include('allauth.urls')),  # for allauth URLs

    # User account
    path('home/user_account/', include('src.apps.accounts.urls')),

    # public url conf
    path('', include('src.apps.public.urls')),
    path('home/', include('src.apps.public.urls')),

    # product url conf
    path('home/', include('src.apps.products.urls')),

    # order url conf
    path('home/user_account/', include('src.apps.orders.urls')),

    # cart url conf
    path('home/', include('src.apps.cart.urls')),

    # PayStack payment gateway url configuration
    path('home/payment', include('src.apps.payments.urls'))
]

# Add Debug Toolbar URLs in debug mode
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # import debug_toolbar
    # urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

src/apps/products/models.py
from django.db import models
from django.utils.text import slugify
from django.core.validators import MinValueValidator
from django.conf import settings
from cloudinary.models import CloudinaryField
import random

# brand model
class Brand(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(unique=True, blank=True)
    # logo = models.ImageField(upload_to='brands/', null=True, blank=True)
    logo = CloudinaryField('image', folder='brands', null=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
          self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

# category model
class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(unique=True, blank=True)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')
    # image = models.ImageField(upload_to='category/', null=True, blank=True)
    image = CloudinaryField('image', folder='category', null=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
          self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name  

# top categories model
class TopCategory(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='top_category')
    created_at = models.DateField(auto_now_add=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.category.name} - Top Category'

# random skull for product
def create_product_random_skull():
    return ''.join(random.choices('0123456789abcdefghijklmnopqrstuvwxyz', k=10))

# product model
class Product(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(unique=True, blank=True)
    sku = models.CharField(max_length=20, unique=True, default=create_product_random_skull)
    brand = models.ForeignKey(Brand, on_delete=models.PROTECT)
    category = models.ManyToManyField(Category, related_name='product_category')
    base_price = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(0)])
    discount_price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    description = models.TextField()
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
  
    def save(self, *args, **kwargs):
        if not self.slug:
            base_slug = slugify(self.name)
            unique_slug = base_slug
            num = 1
            while Product.objects.filter(slug=unique_slug).exists():
              unique_slug = f"{base_slug}-{num}"
              num += 1
            self.slug = unique_slug
        super().save(*args, **kwargs)

    @property
    def current_price(self):
        return self.discount_price if self.discount_price else self.base_price

    @property
    def average_rating(self):
        ratings = self.rating.all()
        if not ratings.exists():
            return 0
        return round(sum(r.stars for r in ratings) / ratings.count(), 1)
    
    def average_rating_int(self):
        return int(self.average_rating or 0)

    @property
    def rating_count(self):
        return self.rating.all().count()
    
    def __str__(self):
        return f"{self.name} ({self.sku})"

# product colors type
class ProductColor(models.Model):
    name = models.CharField(max_length=20)
    hex_color = models.CharField(max_length=7, help_text='E.G., #FFF')

    def __str__(self):
        return self.name

# products specifications 
class ProductSpecification(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='specification')
    memory = models.CharField(blank=True, null=True)
    size = models.CharField(blank=True, null=True)
    storage = models.CharField(blank=True, null=True)

    class Meta:
        unique_together = ('product', 'memory', 'size', 'storage')

    def __str__(self):
        return self.product.name
    

# product badge
class Badge(models.Model):
    BADGE_TYPE = [
        ('sale', 'SALE'),
        ('hot', 'HOT'),
        ('new', 'NEW'),
        ('best_deal', 'BEST DEAL'),
        ('sold_out', 'SOLD OUT')
    ]

    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='product_badge')
    bade_type = models.CharField(max_length=20, choices=BADGE_TYPE)
    is_active = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.bade_type}"

class ProductVariant(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='variant')
    color = models.ForeignKey(ProductColor, on_delete=models.CASCADE, null=True, blank=True)
    badge = models.ManyToManyField(Badge)
    stock = models.PositiveIntegerField(default=0)
    price_adjustment = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    is_default = models.BooleanField(default=False)

    @property
    def final_price(self):
        return self.product.current_price + self.price_adjustment
    
    @property
    def availability(self):
        if self.stock > 20:
            return "In Stock"
        elif self.stock > 1:
            return f"Only {self.stock} product Left"
        return "Out of Stock"

    def __str__(self):
        return f"{self.product.name} - {self.color}"

class ProductImage(models.Model):
    variant = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='images')
    is_featured = models.BooleanField(default=False)
    order = models.PositiveIntegerField(default=0)
    # image = models.ImageField(upload_to='products/')
    image = CloudinaryField('image', folder='products')

    class Meta:
        ordering = ['order']

    def __str__(self):
        return f"Image for {self.variant}"

# product Highlight
class ProductHighlight(models.Model):
    FEATURES = [
        ('best_deal', 'Best Deals'),
        ('featured_product', 'Featured Products'),
        ('flash_sale_today', 'FLASH SALE TODAY'),
        ('best_sellers', 'BEST SELLERS'),
        ('top_rated', 'TOP RATED'),
        ('new_arrival', 'NEW ARRIVAL')
    ]

    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name='product_feature'
    )
    features = models.CharField(max_length=50, choices=FEATURES, blank=False, null=False)
    is_active = models.BooleanField(default=False)
    date_created = models.DateField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.features}'

# ads for product
class Ad(models.Model):
    POSITION_CHOICES = [
        ('top', 'Top Banner'),
        ('top-right-banner', 'Top Right Banner'),
        ('top-right-two-banner', 'Top Right Two Banner'),
        ('bottom', 'Bottom Banner'),
        ('sidebar', 'Sidebar'),
        ('popup', 'Popup'),
        ('middle_banner', 'Middle Banner'),
    ]

    # badge = models.OneToOneField(Badge, on_delete=models.PROTECT, null=True, blank=True)
    highlight = models.OneToOneField(
        ProductHighlight, on_delete=models.PROTECT, related_name='product_highlight',
        null=True, blank=True
    )
    title = models.CharField(max_length=200, blank=True, null=True)
    name = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    # image = models.ImageField(upload_to='ads/', null=True, blank=True)
    image = CloudinaryField('image', folder='ads', null=True, blank=True)
    price = models.DecimalField(decimal_places=0, max_digits=10, blank=True, null=True)
    url = models.URLField(blank=True, null=True)
    position = models.CharField(max_length=20, choices=POSITION_CHOICES)
    is_active = models.BooleanField(default=True)
    category = models.ForeignKey(
        Category, on_delete=models.PROTECT, related_name='product_ad_category', 
        null=True, blank=True
    )
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

# product rating
class ProductRating(models.Model):
    user = models.ForeignKey('accounts.CustomUser', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='rating')
    stars = models.PositiveIntegerField(choices=[(i, str(i)) for i in range(1, 6)])
    review = models.TextField(blank=True)
    date_created = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together =  ['product', 'user']

# product search history for users
class ProductSearchHistory(models.Model):
    user = models.ForeignKey('accounts.CustomUser', on_delete=models.CASCADE)
    product = models.OneToOneField(Product, on_delete=models.CASCADE)
    searched_at = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.user.username

# product comparison
class ProductComparison(models.Model):
    user = models.ForeignKey(
        'accounts.CustomUser', on_delete=models.CASCADE, blank=True, null=True
    )
    session_key = models.CharField(max_length=40, null=True, blank=True) 
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name='product_comparison'
    )
    added_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('session_key', 'product')

    def __str__(self):
        return f"{self.product.name}"

src/apps/products/forms.py
from django import forms
from .models import ProductSpecification

# product specification form
class ReadOnlyProductSpecificationForm(forms.ModelForm):

    class Meta:
        model = ProductSpecification
        fields = ['memory', 'size', 'storage']
        widgets = {
            'memory': forms.TextInput(attrs={'id': 'memory', 'name': 'memory'}),
            'size': forms.TextInput(attrs={'id': 'size', 'name': 'size'}),
            'storage': forms.TextInput(attrs={'id': 'storage', 'name': 'storage'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['readonly'] = True  # makes input text not editable

src/apps/products/templates/products/partials/best_deals.html
{% load static %}

<!-- content here  -->
{% block content %}
<div class="container-homepage-best-deals flex justify-between w-full mt-5">
  {% if best_deals_products %}
  <div class="container-left-bg-product">
    {% if best_hot_deals %}
    <div class="container-product w-100% h-fit">
      <div class="padder-container- w-100% p-2">
        <div class="container-product-img w-full">
          <img
            src="{{ best_hot_deals.images.first.image.url }}"
            alt="{{ best_hot_deals.brand }}"
            class="w-full"
            width="100"
          />

          {% for badge in best_hot_deals.product_badge.all %}
          <div class="container-product-status">
            {% if badge.is_active %}
            <!-- checking badge type -->
            {% if badge.bade_type == 'sold_out' %}
            <p class="sold-out">{{ badge.get_bade_type_display }}</p>

            <!-- off price -->
            {% elif badge.bade_type == 'off-price' %}
            <p class="off-price">{{ badge.get_bade_type_display }}</p>

            <!-- hot -->
            {% elif badge.bade_type == 'hot' %}
            <p class="hot">{{ badge.get_bade_type_display }}</p>

            <!-- best deal -->
            {% elif badge.bade_type == 'best_deal' %}
            <p class="best_deal">{{ badge.get_bade_type_display }}</p>

            <!-- sale -->
            {% elif badge.bade_type == 'sale' %}
            <p class="sale">{{ badge.get_bade_type_display }}</p>

            <!-- new -->
            {% elif badge.bade_type == 'new' %}
            <p class="new">{{ badge.get_bade_type_display }}</p>

            {% endif %}
            <!-- ends -->
            {% endif %}
          </div>
          {% endfor %}

          <div class="container-modal-product">
            <button>
              <svg
                width="20"
                height="20"
                viewBox="0 0 24 24"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path
                  d="M12 20.25C12 20.25 2.625 15 2.625 8.62501C2.625 7.49803 3.01546 6.40585 3.72996 5.53431C4.44445 4.66277 5.43884 4.0657 6.54393 3.84468C7.64903 3.62366 8.79657 3.79235 9.79131 4.32204C10.7861 4.85174 11.5665 5.70972 12 6.75001C12.4335 5.70972 13.2139 4.85174 14.2087 4.32204C15.2034 3.79235 16.351 3.62366 17.4561 3.84468C18.5612 4.0657 19.5555 4.66277 20.27 5.53431C20.9845 6.40585 21.375 7.49803 21.375 8.62501C21.375 15 12 20.25 12 20.25Z"
                  stroke="#191C1F"
                  stroke-width="1.5"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                />
              </svg>
            </button>

            <button>
              <svg
                width="20"
                height="20"
                viewBox="0 0 24 24"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path
                  d="M7.5 19.5C7.91421 19.5 8.25 19.8358 8.25 20.25C8.25 20.6642 7.91421 21 7.5 21C7.08579 21 6.75 20.6642 6.75 20.25C6.75 19.8358 7.08579 19.5 7.5 19.5Z"
                  fill="#191C1F"
                  stroke="#191C1F"
                  stroke-width="1.5"
                />
                <path
                  d="M17.25 21.75C18.0784 21.75 18.75 21.0784 18.75 20.25C18.75 19.4216 18.0784 18.75 17.25 18.75C16.4216 18.75 15.75 19.4216 15.75 20.25C15.75 21.0784 16.4216 21.75 17.25 21.75Z"
                  fill="#191C1F"
                />
                <path
                  d="M3.96562 6.75H20.7844L18.3094 15.4125C18.2211 15.7269 18.032 16.0036 17.7711 16.2C17.5103 16.3965 17.1922 16.5019 16.8656 16.5H7.88437C7.55783 16.5019 7.2397 16.3965 6.97886 16.2C6.71803 16.0036 6.52893 15.7269 6.44062 15.4125L3.04688 3.54375C3.00203 3.38696 2.9073 3.24905 2.77704 3.15093C2.64677 3.05282 2.48808 2.99983 2.325 3H0.75"
                  stroke="#191C1F"
                  stroke-width="1.5"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                />
              </svg>
            </button>

            <a
              href="{% url 'product_details' category_slug=best_hot_deals.category.first.slug child_slug=best_hot_deals.category.last.slug product_slug=best_hot_deals.slug %}"
            >
              <button>
                <svg
                  width="20"
                  height="20"
                  viewBox="0 0 24 24"
                  fill="none"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path
                    d="M12 4.25C4.5 4.25 1.5 12 1.5 12C1.5 12 4.5 19.75 12 19.75C19.5 19.75 22.5 12 22.5 12C22.5 12 19.5 4.25 12 4.25Z"
                    stroke="white"
                    stroke-width="1.5"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                  />
                  <path
                    d="M12 15C13.6569 15 15 13.6569 15 12C15 10.3431 13.6569 9 12 9C10.3431 9 9 10.3431 9 12C9 13.6569 10.3431 15 12 15Z"
                    stroke="white"
                    stroke-width="1.5"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                  />
                </svg>
              </button>
            </a>
          </div>
        </div>

        <div class="container-items pl-1.5 pr-2 pt-2">
          <span class="star-span flex justify-items-start">
            <img src="{% static 'images/svg/Star.svg' %}" alt="star" />
            <img src="{% static 'images/svg/Star.svg' %}" alt="star" />
            <img src="{% static 'images/svg/Star.svg' %}" alt="star" />
            <img src="{% static 'images/svg/Star.svg' %}" alt="star" />
            <img src="{% static 'images/svg/Star.svg' %}" alt="star" />

            <p class="ml-2">(52,677)</p>
          </span>

          <strong>
            <p class="mt-2">{{ best_hot_deals.name }}</p>
          </strong>
          <p class="price">
            {% if best_hot_deals.discount_price %}
            <span class="normal-price mr-3"
              >${{ best_hot_deals.discount_price }}</span
            >
            {% endif %}

            <span class="discount-price">${{ best_hot_deals.base_price }}</span>
          </p>

          <p class="description">{{ best_hot_deals.description }}</p>
        </div>

        <div
          class="container-btns-card mt-2 flex justify-between md:pb-4 pb-7 pl-1.5 pr-5 gap-2"
        >
          <button class="p-2 btn-love-product">
            <img
              src="{% static 'images/svg/Heartdark.svg' %}"
              alt="Heart"
              width="20"
            />
          </button>

          <button class="p-2 add-to-cart_btn flex justify-center">
            <img
              src="{% static 'images/svg/shoppingcart.svg' %}"
              alt="shoppingcart"
              width="20"
            />
            <span class="h-full">Add to card</span>
          </button>

          <button class="p-2 btn-love-product">
            <img src="{% static 'images/svg/Eye.svg' %}" alt="Eye" width="20" />
          </button>
        </div>
      </div>
    </div>
    {% endif %}
  </div>

  <!-- product for best deals here -->
  <div class="container-main-product h-full md:mt-0 mt-5">
    <div class="product-grid md:gap-0 gap-3">
      {% for best_deals_product in best_deals_products %}
      <div class="container-product p-2">
        <div class="container-product-img w-full">
          <img
            src="{{ best_deals_product.images.first.image.url }}"
            alt="{{ best_deals_product.brand }}"
            class="w-full"
            width="100"
          />

          {% for badge in best_deals_product.product_badge.all %}
          <div class="container-product-status">
            {% if badge.is_active %}
            <!-- checking badge type -->
            {% if badge.bade_type == 'sold_out' %}
            <p class="sold-out">{{ badge.get_bade_type_display }}</p>

            <!-- off price -->
            {% elif badge.bade_type == 'off-price' %}
            <p class="off-price">{{ badge.get_bade_type_display }}</p>

            <!-- hot -->
            {% elif badge.bade_type == 'hot' %}
            <p class="hot">{{ badge.get_bade_type_display }}</p>

            <!-- best deal -->
            {% elif badge.bade_type == 'best_deal' %}
            <p class="best_deal">{{ badge.get_bade_type_display }}</p>

            <!-- sale -->
            {% elif badge.bade_type == 'sale' %}
            <p class="sale">{{ badge.get_bade_type_display }}</p>

            <!-- new -->
            {% elif badge.bade_type == 'new' %}
            <p class="new">{{ badge.get_bade_type_display }}</p>

            {% endif %}
            <!-- ends -->
            {% endif %}
          </div>
          {% endfor %}

          <div class="container-modal-product">
            <button>
              <svg
                width="20"
                height="20"
                viewBox="0 0 24 24"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path
                  d="M12 20.25C12 20.25 2.625 15 2.625 8.62501C2.625 7.49803 3.01546 6.40585 3.72996 5.53431C4.44445 4.66277 5.43884 4.0657 6.54393 3.84468C7.64903 3.62366 8.79657 3.79235 9.79131 4.32204C10.7861 4.85174 11.5665 5.70972 12 6.75001C12.4335 5.70972 13.2139 4.85174 14.2087 4.32204C15.2034 3.79235 16.351 3.62366 17.4561 3.84468C18.5612 4.0657 19.5555 4.66277 20.27 5.53431C20.9845 6.40585 21.375 7.49803 21.375 8.62501C21.375 15 12 20.25 12 20.25Z"
                  stroke="#191C1F"
                  stroke-width="1.5"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                />
              </svg>
            </button>

            <button>
              <svg
                width="20"
                height="20"
                viewBox="0 0 24 24"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path
                  d="M7.5 19.5C7.91421 19.5 8.25 19.8358 8.25 20.25C8.25 20.6642 7.91421 21 7.5 21C7.08579 21 6.75 20.6642 6.75 20.25C6.75 19.8358 7.08579 19.5 7.5 19.5Z"
                  fill="#191C1F"
                  stroke="#191C1F"
                  stroke-width="1.5"
                />
                <path
                  d="M17.25 21.75C18.0784 21.75 18.75 21.0784 18.75 20.25C18.75 19.4216 18.0784 18.75 17.25 18.75C16.4216 18.75 15.75 19.4216 15.75 20.25C15.75 21.0784 16.4216 21.75 17.25 21.75Z"
                  fill="#191C1F"
                />
                <path
                  d="M3.96562 6.75H20.7844L18.3094 15.4125C18.2211 15.7269 18.032 16.0036 17.7711 16.2C17.5103 16.3965 17.1922 16.5019 16.8656 16.5H7.88437C7.55783 16.5019 7.2397 16.3965 6.97886 16.2C6.71803 16.0036 6.52893 15.7269 6.44062 15.4125L3.04688 3.54375C3.00203 3.38696 2.9073 3.24905 2.77704 3.15093C2.64677 3.05282 2.48808 2.99983 2.325 3H0.75"
                  stroke="#191C1F"
                  stroke-width="1.5"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                />
              </svg>
            </button>

            <a
              href="{% url 'product_details' category_slug=best_deals_product.category.first.slug child_slug=best_deals_product.category.last.slug product_slug=best_deals_product.slug %}"
            >
              <button>
                <svg
                  width="20"
                  height="20"
                  viewBox="0 0 24 24"
                  fill="none"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path
                    d="M12 4.25C4.5 4.25 1.5 12 1.5 12C1.5 12 4.5 19.75 12 19.75C19.5 19.75 22.5 12 22.5 12C22.5 12 19.5 4.25 12 4.25Z"
                    stroke="white"
                    stroke-width="1.5"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                  />
                  <path
                    d="M12 15C13.6569 15 15 13.6569 15 12C15 10.3431 13.6569 9 12 9C10.3431 9 9 10.3431 9 12C9 13.6569 10.3431 15 12 15Z"
                    stroke="white"
                    stroke-width="1.5"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                  />
                </svg>
              </button>
            </a>
          </div>
        </div>

        <div class="container-items p-1">
          <p class="description-2 mt-2">{{ best_deals_product.name }}</p>

          <p class="price mt-2">
            <span class="discount-price"
              >${{ best_deals_product.base_price }}</span
            >
          </p>
        </div>
      </div>
      {% endfor %}

      <!-- product-grid ends -->
    </div>
  </div>
  {% endif %}
</div>

{% endblock %}